# Lesson 5
### Questions
1. Create an array containing 4 string elements: your first name, your last name, your birth state and your favorite color.
a. Use a numpy function to make all elements uppercase.
b. Use a numpy function to count the number of times the letter “a” appears in each element of your array.
c. Optional: Use a numpy function to find the length of each element in the array. You may need to Google this.

2. Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 41.
a. Use numpy to find the sum and the product of the elements of this array. NOTE: This will require you to convert the elements of your array to floats using the astype method.
b. Use numpy to take the natural log of each element.
c. Optional: The numpy function np.diff finds the difference between adjacent elements of an array. Find the SUM of adjacent elements of this array.

### Responses

In [30]:
#1. Initialize starting packages and array.
import numpy as np
from datascience import *
Problem1_Array=np.array(['Elijah','Evers','Wisconsin','Blue'])

In [31]:
#a. Using the np.char.upper function I can make every letter uppercase.
np.char.upper(Problem1_Array)

array(['ELIJAH', 'EVERS', 'WISCONSIN', 'BLUE'], dtype='<U9')

In [33]:
#b. Using the np.char.count function I can count the number of times a shows up in each element
np.char.count(Problem1_Array,'a')

array([1, 0, 0, 0])

In [41]:
#2. Initializing the array with arange function
Numbers=np.arange(1.,42,4)
Numbers

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41.])

In [42]:
#a. We sum these by using the np.sum function
print(np.sum(Numbers))
# We get the product by using the np.prod function
print(np.prod(Numbers))

231.0
7579867420125.0


In [43]:
#b. We use the np.log function to obtain the natural log of each element
np.log(Numbers)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])